"""add other robot types

Revision ID: 28ad0f531995
Revises: b4d12e6dce4e
Create Date: 2026-01-29 12:56:27.772153

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28ad0f531995"
down_revision: str | Sequence[str] | None = "b4d12e6dce4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_robots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("connection_string", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("serial_number", sa.String(length=255), nullable=False))
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum(
                "SO101_FOLLOWER",
                "SO101_LEADER",
                "TROSSEN_WIDOWXAI_LEADER",
                "TROSSEN_WIDOWXAI_FOLLOWER",
                name="robottype",
            ),
            existing_nullable=False,
        )
        batch_op.drop_column("serial_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_robots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("serial_id", sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "SO101_FOLLOWER",
                "SO101_LEADER",
                "TROSSEN_WIDOWXAI_LEADER",
                "TROSSEN_WIDOWXAI_FOLLOWER",
                name="robottype",
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )
        batch_op.drop_column("serial_number")
        batch_op.drop_column("connection_string")

    # ### end Alembic commands ###
