"""Adds snapshots

Revision ID: 679bf09bd098
Revises: a83d2f5c1878
Create Date: 2025-12-03 10:22:29.373172

"""

import json
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path
from shutil import copytree
from uuid import uuid4

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "679bf09bd098"
down_revision: str | Sequence[str] | None = "a83d2f5c1878"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Adding snapshots table.
    For existing each models a snapshot is created.
    Then the models table is dropped and a new one created so that the snapshot_id can be added with constraint.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    snapshots_table = op.create_table(
        "snapshots",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("dataset_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    conn = op.get_bind()
    model_rows = conn.execute(
        text(
            """SELECT * FROM models INNER JOIN (
              SELECT path as dataset_path, id as d_id FROM datasets
            ) on d_id = models.dataset_id;"""
        )
    ).fetchall()
    snapshots = []
    models = []
    for data_row in model_rows:
        data = data_row._asdict()
        snapshot_path = Path(data["path"]).parent / "snapshot"
        snapshot_id = str(uuid4())
        snapshots.append(
            {
                "id": snapshot_id,
                "path": str(snapshot_path),
                "dataset_id": data["dataset_id"],
            }
        )
        data.pop("d_id")
        data.pop("dataset_path")
        data["properties"] = json.loads(data["properties"])
        data["created_at"] = datetime.fromisoformat(data["created_at"])
        data["updated_at"] = datetime.fromisoformat(data["updated_at"])
        data["snapshot_id"] = snapshot_id
        models.append(data)
        if not snapshot_path.exists():  # in case the snapshot dir exist just take that one.
            copytree(data["path"], snapshot_path)

    op.bulk_insert(snapshots_table, snapshots)

    # Just drop the models table and recreate so that the snapshot_id can be added with nullable=False.
    # This is because sqlite does not allow a column to be altered with not null.
    op.drop_table("models")
    new_models_table = op.create_table(
        "models",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("policy", sa.String(length=255), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("dataset_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("snapshot_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(new_models_table, models)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "snapshot_id")
    op.drop_table("snapshots")
    # ### end Alembic commands ###
