/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Fetch all projects
         */
        get: operations["list_projects_api_projects_get"];
        /**
         * Create Project
         * @description Create a new project
         */
        put: operations["create_project_api_projects_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get project by id
         */
        get: operations["get_project_api_projects__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/datasets/{repo}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Of Project
         * @description Get dataset of project by id
         */
        get: operations["get_dataset_of_project_api_projects__project_id__datasets__repo___id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cameras
         * @description Get all cameras
         */
        get: operations["get_cameras_api_hardware_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Robots
         * @description Get all connected Robots
         */
        get: operations["get_robots_api_hardware_robots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/calibrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lerobot Calibrations
         * @description Get calibrations known to huggingface leRobot
         */
        get: operations["get_lerobot_calibrations_api_hardware_calibrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Identify Robot
         * @description Visually identify the robot by moving given joint on robot
         */
        put: operations["identify_robot_api_hardware_identify_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/camera_feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Camera Feed
         * @description Get a streaming response from the camera
         */
        get: operations["get_camera_feed_api_hardware_camera_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/offer/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offer Camera
         * @description Create a WebRTC offer
         */
        post: operations["offer_camera_api_cameras_offer_camera_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Sdp */
            sdp: string;
            /** Type */
            type: string;
        };
        /** CalibrationConfig */
        CalibrationConfig: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /**
             * Robot Type
             * @enum {string}
             */
            robot_type: "teleoperator" | "robot";
        };
        /** Camera */
        Camera: {
            /**
             * Name
             * @description Camera name
             */
            name: string;
            /**
             * Id
             * @description Either serial id for  RealSense or port for OpenCV
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "RealSense" | "OpenCV";
            default_stream_profile: components["schemas"]["CameraProfile"];
        };
        /** CameraProfile */
        CameraProfile: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps: number;
        };
        /** Dataset */
        Dataset: {
            /** Repo Id */
            repo_id: string;
            /** Episodes */
            episodes: components["schemas"]["Episode"][];
            /** Total Frames */
            total_frames: number;
            /** Features */
            features: string[];
            /** Tasks */
            tasks: string[];
            /** Fps */
            fps: number;
        };
        /** Episode */
        Episode: {
            /** Episode Index */
            episode_index: number;
            /** Length */
            length: number;
            /** Fps */
            fps: number;
            /** Tasks */
            tasks: string[];
            /** Actions */
            actions: number[][];
            /** Modification Timestamp */
            modification_timestamp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Offer */
        Offer: {
            /** Sdp */
            sdp: string;
            /** Type */
            type: string;
            /** Webrtc Id */
            webrtc_id: string;
        };
        /**
         * Project
         * @example {
         *       "id": "7b073838-99d3-42ff-9018-4e901eb047fc",
         *       "name": "SO101 Teleoperation",
         *       "updated_at": "2021-06-29T16:24:30.928000+00:00"
         *     }
         */
        Project: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Name
             * @default Default Name
             */
            name: string;
            /** Updated At */
            updated_at?: string | null;
            /** @description Project config */
            config?: components["schemas"]["ProjectConfig"] | null;
        };
        /**
         * ProjectConfig
         * @example {
         *       "fps": "30"
         *     }
         */
        ProjectConfig: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Fps
             * @description Recording FPS for datasets
             * @default 30
             */
            fps: number;
        };
        /** RobotPortInfo */
        RobotPortInfo: {
            /** Port */
            port: string;
            /** Serial Id */
            serial_id: string;
            /** Device Name */
            device_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAnswer = components['schemas']['Answer'];
export type SchemaCalibrationConfig = components['schemas']['CalibrationConfig'];
export type SchemaCamera = components['schemas']['Camera'];
export type SchemaCameraProfile = components['schemas']['CameraProfile'];
export type SchemaDataset = components['schemas']['Dataset'];
export type SchemaEpisode = components['schemas']['Episode'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaOffer = components['schemas']['Offer'];
export type SchemaProject = components['schemas']['Project'];
export type SchemaProjectConfig = components['schemas']['ProjectConfig'];
export type SchemaRobotPortInfo = components['schemas']['RobotPortInfo'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_projects_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_of_project_api_projects__project_id__datasets__repo___id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                repo: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cameras_api_hardware_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"][];
                };
            };
        };
    };
    get_robots_api_hardware_robots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotPortInfo"][];
                };
            };
        };
    };
    get_lerobot_calibrations_api_hardware_calibrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConfig"][];
                };
            };
        };
    };
    identify_robot_api_hardware_identify_put: {
        parameters: {
            query?: {
                joint?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotPortInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_feed_api_hardware_camera_feed_get: {
        parameters: {
            query: {
                id: string;
                type: "RealSense" | "OpenCV";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_camera_api_cameras_offer_camera_post: {
        parameters: {
            query: {
                camera: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Offer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
