/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Fetch all projects.
         */
        get: operations["list_projects_api_projects_get"];
        /**
         * Create Project
         * @description Create a new project.
         */
        put: operations["create_project_api_projects_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/import_dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Import Dataset
         * @description Set the project from a dataset, only available when config is None.
         */
        put: operations["import_dataset_api_projects__project_id__import_dataset_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Delete a project.
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get project by id.
         */
        get: operations["get_project_api_projects__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/example_teleoperation_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Example Teleoperation Config
         * @description Stub call to get definition in ui, probably will be used later.
         */
        get: operations["get_example_teleoperation_config_api_projects_example_teleoperation_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cameras
         * @description Get all cameras
         */
        get: operations["get_cameras_api_hardware_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Robots
         * @description Get all connected Robots
         */
        get: operations["get_robots_api_hardware_robots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/calibrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lerobot Calibrations
         * @description Get calibrations known to huggingface leRobot
         */
        get: operations["get_lerobot_calibrations_api_hardware_calibrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Identify Robot
         * @description Visually identify the robot by moving given joint on robot
         */
        put: operations["identify_robot_api_hardware_identify_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hardware/camera_feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Camera Feed
         * @description Get a streaming response from the camera
         */
        get: operations["get_camera_feed_api_hardware_camera_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/offer/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offer Camera
         * @description Create a WebRTC offer
         */
        post: operations["offer_camera_api_cameras_offer_camera_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/lerobot_datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leorobot Datasets
         * @description Get all local lerobot datasets from huggingface cache.
         */
        get: operations["list_leorobot_datasets_api_dataset_lerobot_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/{dataset_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Episodes Of Dataset
         * @description Get dataset episodes of dataset by id.
         */
        get: operations["get_episodes_of_dataset_api_dataset__dataset_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Sdp */
            sdp: string;
            /** Type */
            type: string;
        };
        /** CalibrationConfig */
        CalibrationConfig: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /**
             * Robot Type
             * @enum {string}
             */
            robot_type: "teleoperator" | "robot";
        };
        /** Camera */
        Camera: {
            /**
             * Name
             * @description Camera name
             */
            name: string;
            /**
             * Id
             * @description Either serial id for  RealSense or port for OpenCV
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "RealSense" | "OpenCV";
            default_stream_profile: components["schemas"]["CameraProfile"];
        };
        /**
         * CameraConfig
         * @example {
         *       "fps": 30,
         *       "height": 480,
         *       "name": "WebCam",
         *       "port_or_id": "/dev/video0",
         *       "type": "OpenCV",
         *       "use_depth": false,
         *       "width": 640
         *     }
         */
        CameraConfig: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Port Or Id
             * @description Camera port or realsense id
             * @default
             */
            port_or_id: string;
            /**
             * Name
             * @description Camera name
             */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "RealSense" | "OpenCV";
            /**
             * Width
             * @description Frame width
             * @default 640
             */
            width: number;
            /**
             * Height
             * @description Frame height
             * @default 480
             */
            height: number;
            /**
             * Fps
             * @description Camera fps
             * @default 30
             */
            fps: number;
            /**
             * Use Depth
             * @description Use Depth from RealSense
             * @default false
             */
            use_depth: boolean;
        };
        /** CameraProfile */
        CameraProfile: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps: number;
        };
        /**
         * Dataset
         * @example {
         *       "name": "Collect blocks",
         *       "path": "/some/path/to/dataset"
         *     }
         */
        Dataset: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Name
             * @default Default Name
             */
            name: string;
            /** Path */
            path: string;
        };
        /** Episode */
        Episode: {
            /** Episode Index */
            episode_index: number;
            /** Length */
            length: number;
            /** Fps */
            fps: number;
            /** Tasks */
            tasks: string[];
            /** Actions */
            actions: number[][];
            /** Modification Timestamp */
            modification_timestamp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeRobotDatasetInfo */
        LeRobotDatasetInfo: {
            /** Root */
            root: string;
            /** Repo Id */
            repo_id: string;
            /** Total Episodes */
            total_episodes: number;
            /** Total Frames */
            total_frames: number;
            /** Features */
            features: string[];
            /** Fps */
            fps: number;
        };
        /** Offer */
        Offer: {
            /** Sdp */
            sdp: string;
            /** Type */
            type: string;
            /** Webrtc Id */
            webrtc_id: string;
        };
        /**
         * Project
         * @example {
         *       "datasets": [
         *         {
         *           "id": "fec4a691-76ee-4f66-8dea-aad3110e16d6",
         *           "name": "Collect blocks",
         *           "path": "/some/path/to/dataset"
         *         }
         *       ],
         *       "id": "7b073838-99d3-42ff-9018-4e901eb047fc",
         *       "name": "SO101 Teleoperation",
         *       "updated_at": "2021-06-29T16:24:30.928000+00:00"
         *     }
         */
        "Project-Input": {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Name
             * @default Default Name
             */
            name: string;
            /** Updated At */
            updated_at?: string | null;
            /** @description Project config */
            config?: components["schemas"]["ProjectConfig"] | null;
            /**
             * Datasets
             * @description Datasets
             * @default []
             */
            datasets: components["schemas"]["Dataset"][];
        };
        /**
         * Project
         * @example {
         *       "datasets": [
         *         {
         *           "id": "fec4a691-76ee-4f66-8dea-aad3110e16d6",
         *           "name": "Collect blocks",
         *           "path": "/some/path/to/dataset"
         *         }
         *       ],
         *       "id": "7b073838-99d3-42ff-9018-4e901eb047fc",
         *       "name": "SO101 Teleoperation",
         *       "updated_at": "2021-06-29T16:24:30.928000+00:00"
         *     }
         */
        "Project-Output": {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Name
             * @default Default Name
             */
            name: string;
            /** Updated At */
            updated_at?: string | null;
            /** @description Project config */
            config?: components["schemas"]["ProjectConfig"] | null;
            /**
             * Datasets
             * @description Datasets
             * @default []
             */
            datasets: components["schemas"]["Dataset"][];
        };
        /**
         * ProjectConfig
         * @example {
         *       "cameras": [
         *         {
         *           "fps": 30,
         *           "height": 480,
         *           "name": "WebCam",
         *           "port_or_id": "/dev/video0",
         *           "type": "OpenCV",
         *           "use_depth": false,
         *           "width": 640
         *         }
         *       ],
         *       "fps": "30"
         *     }
         */
        ProjectConfig: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Fps
             * @description Recording FPS for datasets
             * @default 30
             */
            fps: number;
            /**
             * Cameras
             * @description Project cameras
             * @default []
             */
            cameras: components["schemas"]["CameraConfig"][];
        };
        /** RobotConfig */
        RobotConfig: {
            /**
             * Id
             * @description Robot calibration id
             */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "follower" | "leader";
            /**
             * Serial Id
             * @description Serial port id
             */
            serial_id: string;
        };
        /** RobotPortInfo */
        RobotPortInfo: {
            /** Port */
            port: string;
            /** Serial Id */
            serial_id: string;
            /** Device Name */
            device_name: string;
        };
        /** TeleoperationConfig */
        TeleoperationConfig: {
            /** Task */
            task: string;
            /** Dataset Id */
            dataset_id: string | null;
            /** Cameras */
            cameras: components["schemas"]["CameraConfig"][];
            /** Robots */
            robots: components["schemas"]["RobotConfig"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAnswer = components['schemas']['Answer'];
export type SchemaCalibrationConfig = components['schemas']['CalibrationConfig'];
export type SchemaCamera = components['schemas']['Camera'];
export type SchemaCameraConfig = components['schemas']['CameraConfig'];
export type SchemaCameraProfile = components['schemas']['CameraProfile'];
export type SchemaDataset = components['schemas']['Dataset'];
export type SchemaEpisode = components['schemas']['Episode'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaLeRobotDatasetInfo = components['schemas']['LeRobotDatasetInfo'];
export type SchemaOffer = components['schemas']['Offer'];
export type SchemaProjectInput = components['schemas']['Project-Input'];
export type SchemaProjectOutput = components['schemas']['Project-Output'];
export type SchemaProjectConfig = components['schemas']['ProjectConfig'];
export type SchemaRobotConfig = components['schemas']['RobotConfig'];
export type SchemaRobotPortInfo = components['schemas']['RobotPortInfo'];
export type SchemaTeleoperationConfig = components['schemas']['TeleoperationConfig'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"][];
                };
            };
        };
    };
    create_project_api_projects_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_dataset_api_projects__project_id__import_dataset_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeRobotDatasetInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_example_teleoperation_config_api_projects_example_teleoperation_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleoperationConfig"];
                };
            };
        };
    };
    get_cameras_api_hardware_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"][];
                };
            };
        };
    };
    get_robots_api_hardware_robots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotPortInfo"][];
                };
            };
        };
    };
    get_lerobot_calibrations_api_hardware_calibrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConfig"][];
                };
            };
        };
    };
    identify_robot_api_hardware_identify_put: {
        parameters: {
            query?: {
                joint?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotPortInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_feed_api_hardware_camera_feed_get: {
        parameters: {
            query: {
                id: string;
                type: "RealSense" | "OpenCV";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_camera_api_cameras_offer_camera_post: {
        parameters: {
            query: {
                camera: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Offer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leorobot_datasets_api_dataset_lerobot_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeRobotDatasetInfo"][];
                };
            };
        };
    };
    get_episodes_of_dataset_api_dataset__dataset_id__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Episode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
